<?php
// module/Album/view/album/album/index.phtml:

$title = 'Cart Details';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
	if (!isset($this->layout()->cart_id)) {
		?>
			<div class="col-sm-12">
				<div class="alert alert-danger">No item(s) in your cart</div>
			</div>
		<?php
	} else {
		?>

<table class="table table-hover table-condensed">
	<thead>
		<tr>
			<th>Product</th>
			<th>&nbsp;</th>
			<th>Quantity</th>
			<th>Price</th>
		</tr>
	</thead>
	<tbody>
		<?php 
			
			foreach ($cartitem as $cartitems) {
		?>
		<tr>
			<td>				
				<img class="thumbnail" src="<?php echo $this->basePath($cartitems->product_thumbnail);?>">
			</td>
			<td>
				<h4><?php echo $cartitems->product_name; ?></h4>
				<p><?php echo $cartitems->product_desc; ?></p>
				<p><?php echo "$ ".$cartitems->unit_price; ?></p>
			</td>
			<td>
				<h4><?php echo $cartitems->qty; ?></h4>
			</td>
			<td>
				<h4><?php echo "$ ".$cartitems->price; ?></h4>
			</td>
		</tr>
		<?php	
			}
		?>
	</tbody>
</table>

<div class="col-xs-12">
	<div class="col-xs-3 pull-right">
		<div class="col-xs-7">
			<h4>Subtotal </h4>
		</div>

		<div class="col-xs-5">
			<h4>
				<?php
					$total = 0;
					foreach ($cartitem as $value) {
						$total += $value->price;
					}
					echo "$ ".number_format((float)$total, 2, '.', '');
				?>
			</h4>
		</div>
	</div>
</div>

<div class="col-xs-12">
	<div class="col-xs-3 pull-right">
		<div class="col-xs-7">
			<h4>Shipping </h4>
		</div>

		<div class="col-xs-5">
			<h4>
				<?php
					$total = 0;
					echo "$ ".number_format((float)$total, 2, '.', '');
				?>
			</h4>
		</div>
	</div>
</div>

<div class="col-xs-12">
	<div class="col-xs-3 pull-right c">
		<div class="col-xs-7">
			<h4>Grand Total </h4>
		</div>

		<div class="col-xs-5">
			<h4>
				<?php
					$total = 0;
					foreach ($cartitem as $value) {
						$total += $value->price;
					}
					echo "$ ".number_format((float)$total, 2, '.', '');
				?>
			</h4>
		</div>

		<a href="<?php echo isset($this->layout()->customer_id) ? $this->url('product', array('action' => 'shipping')) : $this->url('customer', array('action' => 'login')) ?>">
			<div class="col-xs-12 btn btn-success">
				CheckOut
			</div>
		</a>	
	</div>
</div>
<?php
}
?>
