<?php
// module/Album/view/album/album/index.phtml:

$title = 'Products';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php 
	foreach ($products as $product) {
?>
	<div class="col-xs-12">

		<div class="col-xs-2">
			<a href="<?php echo $this->url('product', array('action'=>'view', 'id' => $product->product_id)) ?>">
				<img class="thumbnail" src="<?php echo $product->product_thumbnail; ?>">
			</a>
		</div>

		<div class="col-xs-10">
			<div class="col-xs-12">
				<div class="col-xs-3">
					<label> Product Name: </label> 
				</div>
				<div class="col-xs-9">
					<span> <?php echo $product->product_name; ?></span>
				</div>
				
			</div>
			
			<div class="col-xs-12">

				<div class="col-xs-3">
					<label> Product Description: </label>
				</div>
				<div class="col-xs-9">
					<span> <?php echo $product->product_desc; ?></span>
				</div>
				 
			</div>

			<div class="col-xs-12">

				<div class="col-xs-3">
					<label> Product Price: </label>
				</div>
				<div class="col-xs-9">
					<span> <?php echo "$" . $product->price; ?></span>
				</div>
				 
			</div>
		</div>
	</div>
<?php		
	}
?>