<?php
// module/Album/view/album/album/index.phtml:

$title = 'Cart Payment Details';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table table-hover table-condensed">
	<thead>
		<tr>
			<th>Product</th>
			<th>&nbsp;</th>
			<th>Quantity</th>
			<th>Price</th>
		</tr>
	</thead>
	<tbody>
		<?php 
			
			foreach ($cartItemdetails as $cartitems) {
		?>
		<tr>
			<td>				
				<img class="thumbnail" src="<?php echo $this->basePath($cartitems->product_thumbnail);?>">
			</td>
			<td>
				<h4><?php echo $cartitems->product_name; ?></h4>
				<p><?php echo $cartitems->product_desc; ?></p>
				<p><?php echo "$ ".$cartitems->unit_price; ?></p>
			</td>
			<td>
				<h4><?php echo $cartitems->qty; ?></h4>
			</td>
			<td>
				<h4><?php echo "$ ".$cartitems->price; ?></h4>
			</td>
		</tr>
		<?php	
			}
		?>
	</tbody>
</table>

<div class="col-xs-12">
	<div class="col-xs-3 pull-right">
		<div class="col-xs-7">
			<h4>Subtotal </h4>
		</div>

		<div class="col-xs-5">
			<h4>
				<?php
					//$sub_total = $value->sub_total;
					echo "$ ".number_format((float)$cartDetails->sub_total, 2, '.', '');
				?>
			</h4>
		</div>
	</div>
</div>

<div class="col-xs-12">
	<div class="col-xs-3 pull-right">
		<div class="col-xs-7">
			<h4>Shipping </h4>
		</div>

		<div class="col-xs-5">
			<h4>
				<?php
					echo "$ ".number_format((float)$cartDetails->shipping_total, 2, '.', '');
				?>
			</h4>
		</div>
	</div>
</div>

<div class="col-xs-12">
	<div class="col-xs-3 pull-right c">
		<div class="col-xs-7">
			<h4>Grand Total </h4>
		</div>

		<div class="col-xs-5">
			<h4>
				<?php
					echo "$ ".number_format((float)$cartDetails->total_amount, 2, '.', '');
				?>
			</h4>
		</div>

		<a href="<?php echo $this->url('product', array('action' => 'orderconfirmation')) ?>">
			<div class="col-xs-12 btn btn-success">
				CheckOut
			</div>
		</a>	
	</div>
</div>
