<?php
// module/Album/view/album/album/index.phtml:

$title = 'All Reviews';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('product', array('action'=>'add'));?>">Add new review</a>
</p>

<?php 
	foreach ($products as $product) {
?>
	<div class="col-xs-12">

		<div class="col-xs-6">
			<a href="<?php echo $this->url('product', array('action'=>'view', 'id' => $product->product_id)) ?>">
				<img src="<?php echo $this->basePath($product->product_image);?>">
			</a>
		</div>

		<div class="col-xs-6">
			<div class="col-xs-12">
				<div class="col-xs-6">
					<label> Product Name: </label> 
				</div>
				<div class="col-xs-6">
					<span> <?php echo $product->product_name; ?></span>
				</div>
				
			</div>
			
			<div class="col-xs-12">

				<div class="col-xs-6">
					<label> Product Description: </label>
				</div>
				<div class="col-xs-6">
					<span> <?php echo $product->product_desc; ?></span>
				</div>
				 
			</div>

			<div class="col-xs-12">

				<div class="col-xs-6">
					<label> Product Price: </label>
				</div>
				<div class="col-xs-6">
					<span> <?php echo "$" . $product->price; ?></span>
				</div>
				 
			</div>
		</div>
	</div>
<?php		
	}
?>